### PR TITLE
Add nice liveness graph output to the Polonius CLI wrapper

### PR DESCRIPTION
**Pull request by albins**
Uses Petgraph to reduce boring parts (completely linear sections with no changes in liveness of any variable) of the CFG; adds liveness edges with nice colours.

This only affects the Polonius CLI wrapper.

### CODE REVIEW

**Comment by shepmaster** [comment]
No pretty graphic to show off the results? boooooo 😉

**Comment by albins** [comment]
@shepmaster: I forgot!
liveness

**Comment by albins** [comment]
There is a problem with the labels of compacted nodes in the CFG: it shows them as first--last (when it's more than two), but it orders them by sorting the indices. Apparently, they are not guaranteed to translate to actually consecutive program points, but as far as I can tell there is almost nothing I can do about this.

**Comment by albins** [comment]
Apparently, I snuck these changes in via another pull request for liveness changes. :)

**Pull request closed without merging**
