### PR TITLE
[WIP] Describe standard proceedure for writing and running tests in the book

### PR DESCRIPTION
**Pull request by albins**
(Perhaps mainly for myself, who keeps forgetting)

### CODE REVIEW

**Comment by albins** [comment]
Oh no I'll have to rebase this on the upstream master.

**Comment by shepmaster** [comment]
You don’t seem to have added the testing.md file to this commit...?

**Comment by albins** [comment]
Correct, I forgot 🤦🏽‍♀️

**Comment by nikomatsakis** [comment]
Should we merge?

**Comment by albins** [comment]
I guess we can given that there’s no point in describing polonius-parser at this point.

**Pull request merged**
