### PR TITLE
Build the book on CI

### PR DESCRIPTION
**Pull request by lqd**
Try to build the mdbook on CI and autodeploy it from there

### CODE REVIEW

**Comment by lqd** [comment]
According to [the doc](https://rust-lang-nursery.github.io/mdBook/continuous-integration.html) this _should be_ how it's done, what do you think @pietroalbini ? :)

**Comment by pietroalbini** [comment]
We have a [different deployment code](https://github.com/rust-lang/infra-team/blob/master/guidelines/static-websites.md#configuring-travis-ci) for the rust-lang org. You need to replace the `deploy:` block with:

```yaml
env:
  RUSTINFRA_DEPLOY_DIR: book/book
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
```

**Comment by lqd** [comment]
Ah thank you, I thought it was somewhat specific to `hugo` (as in the `compiler-team` repo), or at the very least unrelated to `mdbook` deployments since the set-up seemed different at first glance in the `rustc-guide` repo.

I'll change this ASAP.

**Comment by pietroalbini** [comment]
That piece of infra is relatively new, so it's not surprising most of our repositories don't use it.

**Comment by lqd** [comment]
Thanks a lot for the help @pietroalbini !

I guess it's time to ... try ? :)

**Pull request merged**
